app:
  replicas: 1
  name: order-management-ms
  configPath: /app/config
  port: 8086


configMap:
  name: order-management-config

image:
  repository: abw12/order-management-ms # update image name
  tag: v1
postgres:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  host: db-postgresql-blr1-43787-do-user-15428494-0.c.db.ondigitalocean.com
  port: 25060
  db: absolutehealth
