server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/absolutehealth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      client:
        config:
          product-inventory-controller:
            url: http://product-catalog:8090/catalog/inventory
          product-catalog-controller:
            url: http://localhost:8090/catalog/product
springdoc:
  api-docs:
    path: /v3/order-mgmt-docs

payment:
  razorpay:
    merchantId: NKZ5A3skq8OknJ
    api:
      createOrderURL: https://api.razorpay.com/v1/orders
      keyId: rzp_test_qfAoOQO3Kpd4KG
      secret: qWJOEBapbc8auZJ8D23EUFKV
