apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  application-dev.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service:5432/absolutehealth
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
      cloud:
        openfeign:
          client:
            config:
              product-inventory-controller:
                url: http://product-catalog:8090/catalog/inventory
    server:
      port: {{ .Values.app.port }}
    springdoc:
      api-docs:
        path: /v3/order-mgmt-docs
